version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: github-feed
    binary: github-feed
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Ignore arm64 for Windows (not commonly supported)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    # Use zip for Windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: zveinn
    name: github-feed
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ### macOS
    ```bash
    # Intel Mac
    tar -xzf github-feed_{{.Version}}_Darwin_x86_64.tar.gz
    chmod +x github-feed
    sudo mv github-feed /usr/local/bin/

    # Apple Silicon Mac
    tar -xzf github-feed_{{.Version}}_Darwin_arm64.tar.gz
    chmod +x github-feed
    sudo mv github-feed /usr/local/bin/
    ```

    ### Linux
    ```bash
    # x86_64
    tar -xzf github-feed_{{.Version}}_Linux_x86_64.tar.gz
    chmod +x github-feed
    sudo mv github-feed /usr/local/bin/

    # ARM64
    tar -xzf github-feed_{{.Version}}_Linux_arm64.tar.gz
    chmod +x github-feed
    sudo mv github-feed /usr/local/bin/
    ```

    ### Windows
    Download the appropriate `.zip` file, extract it, and add the `github-feed.exe` to your PATH.
